#!/usr/bin/env bash
# a script that modify localhost and facebok addresses
cp /etc/hosts /etc/host.backup
sed -i 'localhost' /etc/hosts
sed -i 'facebook.com' /etc/hosts
echo '127.0.0.2 localhost' >> /etc/hosts
echo '8.8.8.8 facebook.com' >> /etc/hosts