#!/usr/bin/env bash
# A script to modify localhost and facebook.com entries
cp /etc/hosts /etc/hosts.backup
sed -i 's/^.*localhost.*/127.0.0.2     localhost/' /etc/hosts
sed -i 's/^.*facebook.com.*/8.8.8.8       facebook.com/' /etc/hosts
grep -qxF '127.0.0.2     localhost' /etc/hosts || echo '127.0.0.2     localhost' >> /etc/hosts
grep -qxF '8.8.8.8       facebook.com' /etc/hosts || echo '8.8.8.8       facebook.com' >> /etc/hosts
